### ISSUE TITLE
Data table is not displayed in the Metadata tab of the database until the user refreshes and re-selects the database.

### ISSUE THREAD

**Issue by Hanumant2828** [SEMOSS/semoss-ui#1770]
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1. Open the application.
2. Create a new database.
3. Open the Metadata tab for the newly created database.
4. Observe the data
5. Click on the "Refresh Data" button.
6. Select a table name from the available list.
7. Click "Apply."

### Expected Result

The Metadata tab should display relevant data for the newly created database immediately upon opening.

### Actual Results

No data is displayed in the Metadata tab after creating a new database.

### Additional Context

<img width="1536" height="631" alt="Image" src="https://github.com/user-attachments/assets/a6831a01-aa0c-41c5-853a-eb2801d21849" />

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

**Comment by Hanumant2828** [comment]
@jasneetkaurdeloitte @roxyramos @rameshpaulraj @Pranchaudhari Can you please check this bug and confirm?

**Comment by Gunasrini18** [comment]
Hi Team,
I have fixed the above mentioned issue, raised a draft PR, and shared it for internal review.
https://github.com/SEMOSS/semoss-ui/pull/1817

@Paulson-Robert, Kindly review and provide the feedback if any.

**Comment by Hanumant2828** [comment]
Hi @Gunasrini18 
Dev team said issue #1791 would be fixed as part of this ticket, but it’s still not resolved. Could you please provide an update?

<img width="1536" height="631" alt="Image" src="https://github.com/user-attachments/assets/8e4561b1-df3f-46f6-9a52-469db0daba38" />

**Comment by Hanumant2828** [comment]
I have tested this issue, and it is now fixed.

<img width="1536" height="631" alt="Image" src="https://github.com/user-attachments/assets/6d3b8717-9cf8-418c-a038-1873a64b9843" />

**Comment by Gunasrini18** [comment]
Hi @Hanumant2828 Thank you for confirming that ticket #1770 is working as expected. However, as you mentioned, ticket #1791 is still not working in some scenarios. I’ll be working on this and will create a separate PR to address it.
