### ISSUE TITLE
Selected Database Columns Not Displayed in Import Popup During Notebook Creation

### ISSUE THREAD

**Issue by Hanumant2828** [SEMOSS/semoss-ui#1791]
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1. Open the application
2. Navigate to Database page and create database
3. Navigates to App and create drag and drop app
4. Open created app and create notebook
5. Mouse hover below existing cell 
6. Select Data import option and select 'From Data Catalog' option from list
7. Select Database from import data dropdown

### Expected Result

The popup window should display the columns selected from the database, allowing the user to import data.

### Actual Results

The popup window does not reflect the columns from the database.

### Additional Context

<img width="1536" height="631" alt="Image" src="https://github.com/user-attachments/assets/4d0268de-198e-4a90-9739-b0d80f90af17" />

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

**Comment by Hanumant2828** [comment]
@jasneetkaurdeloitte @roxyramos @rameshpaulraj @Pranchaudhari Could you please prioritize the review of the above defect?

**Comment by Hanumant2828** [comment]
We identified the root cause of the issue. The database was not refreshed, so we need to refresh it from the metadata and save it. After that, it works correctly.

<img width="1905" height="846" alt="Image" src="https://github.com/user-attachments/assets/e941bad3-f8a6-4b7d-8da1-dc03cb633549" />

cc: @ehynd @jasneetkaurdeloitte @roxyramos @rameshpaulraj

**Comment by JaganSomannaKanini** [comment]
Hi @ehynd @rameshpaulraj , as @Gunasrini18 is working on ticket #1770 this issue will also be resolved with that ticket itself.

**Comment by Hanumant2828** [comment]
As per last comment,  this issue would be fixed as part of ticket #1770, but it’s still not resolved. The issue is still present. Could you please check?

<img width="1536" height="631" alt="Image" src="https://github.com/user-attachments/assets/a3ad98df-1ee1-4a2e-a978-1e95aebe2929" />

cc: @rameshpaulraj @ehynd @JaganSomannaKanini

**Comment by Gunasrini18** [comment]
Hi @Hanumant2828 We initially thought this issue would be resolved with ticket #1770, but in some scenarios, it’s still not working as expected. I’ll be working on this and will create a separate PR to address it.
