### ISSUE TITLE
Multiple issues observed while creating and managing jobs on the Settings page

### ISSUE THREAD

**Issue by BhaktiKanini** [SEMOSS/semoss-ui#2113]
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1.Login to the application.
2.Navigate to Settings → Job Management.
3.Create a new job with valid details.
4.Edit the created job and try updating the Time Zone.
5.Run one specific job and observe the execution behavior.
6.Check the Created Job Count display on the UI

### Expected Result

1.The Time Zone should update correctly after editing a job.
2.Running one job should trigger only the selected job, not all. and history also check after run the job
3.The Created Job Count should be clearly visible and match the Figma design.
4.Filed text should be match with Figma
5.Resume Symbol should match with Figma
6..Pixel text box should match with Figma
7.Failed Count should update properly

### Actual Results

1.The Time Zone does not update after editing.
2.Executing one job triggers all jobs.
3.The Created Job Count appears blurred and misaligned with the design reference.
4.Check The Filed text is not matching with Figma
5.Resume Symbol not match with Figma
6.Pixel text box not match with Figma
7.Failed Count is not updating properly

### Additional Context

<img width="1918" height="847" alt="Image" src="https://github.com/user-attachments/assets/5a8a2811-cd6e-49e5-b4a6-515f542a3410" />

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

**Comment by Gowrishankar-Palanisamy** [comment]
Hi @BhaktiKanini ,

Fixed all the issues, Kindly take a look

**Comment by BhaktiKanini** [comment]
@Gowrishankar-Palanisamy 
I retested this ticket, but the issue persists. The count is still not updating, and the pixel alignment is not matching the Figma design

CC: @rameshpaulraj

**Comment by Gowrishankar-Palanisamy** [comment]
@BhaktiKanini ,
Fixed the above mentioned bugs, Kindly test

**Comment by BhaktiKanini** [comment]
@Gowrishankar-Palanisamy  Observe issue are tested it is working fine as expectaion
<img width="1920" height="911" alt="Image" src="https://github.com/user-attachments/assets/79f5d50a-b560-4e2f-bd29-21e9f5e5f69f" />
After run job
<img width="1920" height="907" alt="Image" src="https://github.com/user-attachments/assets/98d63c53-343e-4094-8c47-5d0dd6d5f533" />

Cc: @rameshpaulraj @Pranchaudhari
